### ISSUE TITLE
[Issue] New installed apps from ARCH /AUR not showed on Toggle Overview/Lancher

### ISSUE THREAD

**Issue by zydnrbrn** [end-4/dots-hyprland#451] opened 2024-05-01 03:56 UTC
- **I have read the [Usage](https://end-4.github.io/dots-hyprland-wiki/en/i-i/02usage) and the [Troubleshooting](https://end-4.github.io/dots-hyprland-wiki/en/i-i/03troubleshooting) pages of the wiki**
- **I have made sure that both my config and system packages are up to date**
- Linux distro: EndeavourOS
- Distributor ID:	EndeavourOS
Description:	EndeavourOS Linux
Release:	rolling
Codename:	rolling

---
## The issue
I've been installed google chrome, spotify and vscode with yay, but not showed on launcher

<details>
<summary>Click to expand</summary>

```plain
Paste your log here
```

</details>

**Comment by clsty** [comment] 2024-05-01 04:04
Duplicate of #444

**Closed by clsty** 2024-05-01 04:04 UTC
