### ISSUE TITLE
[Issue] after finishing the installation I got This

### ISSUE THREAD

**Issue by taoki123** [end-4/dots-hyprland#939] opened 2024-11-11 09:39 UTC
- I have read the Usage and Troubleshooting pages of the wiki: https://end-4.github.io/dots-hyprland-wiki/en/i-i/04troubleshooting/
- I have made sure that both my config and system packages are up to date
- Linux distro: 

---
## The issue

<details>
<summary>Logs</summary>

```plain
Paste logs here
```
![image](https://github.com/user-attachments/assets/29062455-aad5-4c34-baa7-56c5123de1ff)
</details>

**Comment by taoki123** [comment] 2024-11-11 21:09
Ohk bro it working now though I didn't do anything but another problem am having is that the screen resolution it gave is too small and if I try changing it it not changing it just still there

**Comment by Makrennel** [comment] 2024-11-11 22:49
Put your monitor configuration in `.config/hypr/custom/general.conf`, refer to [the Hyprland wiki](https://wiki.hyprland.org/Configuring/Monitors/) for the specifics of how to write it and get the correct display outputs to use.

The theme is autogenerated based on your current wallpaper - use `Control + Super + T` to choose your wallpaper. I believe `Super + Comma` also allows you to choose between a set of variants of the theme generated on your wallpaper.

**Comment by taoki123** [comment] 2024-11-12 04:24
Bro I think the mistake I made was that I installed the script on my gnome so I think built it self with it is there a way that I can uninstall and reinstall??? It on hyprland

**Comment by taoki123** [comment] 2024-11-12 16:20
> Put your monitor configuration in `.config/hypr/custom/general.conf`, refer to [the Hyprland wiki](https://wiki.hyprland.org/Configuring/Monitors/) for the specifics of how to write it and get the correct display outputs to use.
> 
> 
> 
> The theme is autogenerated based on your current wallpaper - use `Control + Super + T` to choose your wallpaper. I believe `Super + Comma` also allows you to choose between a set of variants of the theme generated based on your wallpaper.

Bro I just re install it still small but i got promoted with a new problem which just put up when I allow transparency ![image](https://github.com/user-attachments/assets/3194862a-46f9-4124-8294-bac4be190659)![image](https://github.com/user-attachments/assets/b54fd4a7-7c21-4900-b585-d835144fe4d6)

**Comment by xiadnoring** [comment] 2024-11-12 16:48
Hi! It maybe caused by the absence of wallpaper

**Comment by taoki123** [comment] 2024-11-12 17:25
> Hi! It maybe caused by the absence of wallpaper

Ohk will try add a wallpaper

**Comment by taoki123** [comment] 2024-11-13 17:27
![image](https://github.com/user-attachments/assets/34c69774-f9ae-4749-bf7f-245683926508)

Just outta curiosity isn't there any other themes other than this pls cuz when I uncommitted those in the config files nothing happened what I mean is something that will change the look of the waybar

**Comment by Makrennel** [comment] 2024-11-15 02:28
Again, themes are generated based on the wallpaper you select with `SUPER + SHIFT + T` and you can choose a generated variant theme using `SUPER + COMMA`. Other than that, I don't think there's a way of directly setting a theme. These dotfiles don't use waybar at all, it's a custom AGS setup.

**Comment by Pharmaracist** [comment] 2024-11-16 23:47
close the issue

**Comment by Pharmaracist** [comment] 2024-11-21 18:46
nah its just the new hyprland version

**Closed** 2024-11-28 00:11 UTC
