### ISSUE TITLE
[Issue] Animation Issue

### ISSUE THREAD

**Issue by JayaDeep11** [end-4/dots-hyprland#389] opened 2024-04-05 13:05 UTC
- **(For usage) I have read the [wiki](https://end-4.github.io/dots-hyprland-wiki/en/i-i/02usage)**
- **(For troubleshooting) I have read the [wiki](https://end-4.github.io/dots-hyprland-wiki/en/i-i/03troubleshooting)**
- Linux distro:  Arch Linux

---
## The issue

I got No such a Animation error from general.conf file

<details>
<summary>Click to expand</summary>

![image](https://github.com/end-4/dots-hyprland/assets/110987107/5f195877-e5ae-4729-a8ae-64c331c302df)

</details>

**Comment by end-4** [comment] 2024-04-05 14:34
update hyprland
if `hyprland-git` doesn't work, compile from source:
```bash
cd ~/Downloads
git clone --recursive https://github.com/hyprwm/hyprland && cd hyprland && make all
sudo make install && sudo make installheaders
```

**Comment by Kalidude69** [comment] 2024-04-05 17:33
> ```shell
> sudo make install && sudo make installheaders
> ```

hi there i am   facing the same issue too ```hyprland-git``` is working but the error still continues the same even did the commands specified before still on this state ...

**Comment by b4shful** [comment] 2024-04-05 21:46
I was also facing this issue, I ran the relevant parts of the install script again but I guess running `yay` with `--needed` doesn't necessarily work all that well with hyprland-git from the AUR. I then tried the instructions @end-4 listed but that didn't actually seem to install the compiled from source version (`hyprctl version` was still showing the older version).

I ended up just running `yay -S hyprland-git` to do a reinstall and selecting the clean build option when asked to. This properly installed the latest version and fixed the animations issue.

@end-4 and also @clsty (install script person I believe?): As far as I'm aware, hyprland-git AUR package just compiles from source using the latest github commit at the time of installation, and so updates to the package itself are less frequent (a few per month at most it seems). This might cause some unexpected behaviour as updates to the AUR package don't correspond (and aren't even intended to correspond) to Hyprland updates. The same version of the AUR package can produce different versions of Hyprland all depending on what the latest commit is at the time of installation (or reinstallation). Might be worth looking into ways to solve this?

**Comment by b4shful** [comment] 2024-04-05 23:29
Also an additional note on hyprland versions - there's a `hyprctl version` command which doesn't appear in the help for hyprctl, but it provides useful information on the main Hyprland version and what commit it was built from (or other alternative information if not built from source).

**Comment by clsty** [comment] 2024-04-05 23:37
@ b4shful Done in 3394cad5d8e871afbb03a23476b3e32510173ba8

**Comment by Kalidude69** [comment] 2024-04-06 04:54
yeah clean building from yay solved the issues otherwise i had just commented out the lines before now after clean building it seems to work properly

**Comment by JayaDeep11** [comment] 2024-04-07 19:56
@end-4  

cd ~/Downloads
git clone --recursive https://github.com/hyprwm/hyprland && cd hyprland && make all
sudo make install && sudo make installheaders

after using 

still same error.

**Comment by clsty** [comment] 2024-04-07 22:57
Closing as solved. Feel free to re-open if this still happens. @JayaDeep11

**Closed by clsty** 2024-04-07 22:57 UTC

**Comment by JayaDeep11** [comment] 2024-04-10 10:00
> > ```shell
> > sudo make install && sudo make installheaders
> > ```
> 
> hi there i am facing the same issue too `hyprland-git` is working but the error still continues the same even did the commands specified before still on this state ...

use this command :-

```
hyprctl reload
```

in my case it works :smile:
