### ISSUE TITLE
[Issue] keep system awake button not working

### ISSUE THREAD

**Issue by fruitsaladchan** [end-4/dots-hyprland#494] opened 2024-05-11 19:11 UTC
- **I have read the [Usage](https://end-4.github.io/dots-hyprland-wiki/en/i-i/02usage) and the [Troubleshooting](https://end-4.github.io/dots-hyprland-wiki/en/i-i/03troubleshooting) pages of the wiki**
- **I have made sure that both my config and system packages are up to date**
- Linux distro: EndeavourOS

---
## The issue

 i can hit the coffee button to keep system awake button but it still goes to hyprlock after like 5 min. 

<details>
<summary>Click to expand</summary>

```plain
Paste your log here
```

</details>

**Comment by end-4** [comment] 2024-05-12 00:53
dupe of #469

**Closed by end-4** 2024-05-12 00:53 UTC
