### ISSUE TITLE
ui

### ISSUE THREAD

**Issue by 2445244810** [end-4/dots-hyprland#605] opened 2024-06-11 15:59 UTC
![Uploading 17181215585655623309455462426171.jpg…]()
- **I have read the [Usage](https://end-4.github.io/dots-hyprland-wiki/en/i-i/02usage) and the [Troubleshooting](https://end-4.github.io/dots-hyprland-wiki/en/i-i/03troubleshooting) pages of the wiki**
- **I have made sure that both my config and system packages are up to date**
- Linux distro: 

---
## The issue

<details>
<summary>Click to expand</summary>

```plain
Paste your log here
```

</details>

**Comment by end-4** [comment] 2024-06-12 09:08
what

**Comment by clsty** [comment] 2024-06-12 10:36
The issue is lack of meaning. If you need help, please create a valid issue.
Closing.

**Closed by clsty** 2024-06-12 10:36 UTC
