### ISSUE TITLE
[Issue] how to fix "meson install -c build" has failed

### ISSUE THREAD

**Issue by enrich4real** [end-4/dots-hyprland#194] opened 2024-01-17 16:17 UTC
- **I have read the instructions**
- I am trying to install the dotfiles for illogical impulse and I am a newbie to linux so don't know how to solve this error
---
## The issue
- This error is being shown when installing the files and I don't know what to do
```
- `ninja: Entering directory `/home/prashident/Documents/newdot/dots-hyprland/cache/ags/build'
[1/4] Generating subprojects/gvc/Gvc-1.0.gir...custom command (wrapped by meson to set env)
FAILED: subprojects/gvc/Gvc-1.0.gir 
env PKG_CONFIG_PATH=/home/prashident/Documents/newdot/dots-hyprland/cache/ags/build/meson-uninstalled PKG_CONFIG=/usr/bin/pkg-config CC=cc /usr/bin/g-ir-scanner --quiet --no-libtool --namespace=Gvc --nsversion=1.0 --warn-all --output subprojects/gvc/Gvc-1.0.gir -DWITH_INTROSPECTION --quiet -I/home/prashident/Documents/newdot/dots-hyprland/cache/ags/subprojects/gvc -I/home/prashident/Documents/newdot/dots-hyprland/cache/ags/build/subprojects/gvc --filelist=/home/prashident/Documents/newdot/dots-hyprland/cache/ags/build/subprojects/gvc/libgvc.so.p/Gvc_1.0_gir_filelist --include=Gio-2.0 --include=GObject-2.0 --cflags-begin -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/sysprof-6 -D_REENTRANT -I/usr/include/gobject-introspection-1.0 --cflags-end --add-include-path=/usr/share/gir-1.0 -L/home/prashident/Documents/newdot/dots-hyprland/cache/ags/build/subprojects/gvc --library gvc -lgio-2.0 -lgobject-2.0 -lglib-2.0 -lpulse -lpulse-mainloop-glib -lgirepository-1.0
Traceback (most recent call last):
  File "/usr/bin/g-ir-scanner", line 103, in <module>
    from giscanner.scannermain import scanner_main
  File "/usr/lib/gobject-introspection/giscanner/scannermain.py", line 35, in <module>
    from giscanner.ast import Include, Namespace
  File "/usr/lib/gobject-introspection/giscanner/ast.py", line 29, in <module>
    from .sourcescanner import CTYPE_TYPEDEF, CSYMBOL_TYPE_TYPEDEF
  File "/usr/lib/gobject-introspection/giscanner/sourcescanner.py", line 34, in <module>
    from giscanner._giscanner import SourceScanner as CSourceScanner
ImportError: /usr/lib/gobject-introspection/giscanner/_giscanner.cpython-311-x86_64-linux-gnu.so: undefined symbol: g_string_free_and_steal
[2/4] Generating src/typescript-compile with a custom command
ninja: build stopped: subcommand failed.
Could not rebuild /home/prashident/Documents/newdot/dots-hyprland/cache/ags/build
[./install.sh]: Command "meson install -C build" has failed.
You may need to resolve the problem manually BEFORE repeating this command.
  r = Repeat this command (DEFAULT)
  e = Exit now
  i = Ignore this error and continue (your setup might not work correctly)
 [R/e/i]: 
```

**Comment by eli-schwartz** [comment] 2024-01-17 21:00
Your `/usr/bin/g-ir-scanner` program is broken.

**Comment by Ben-Plagmann** [comment] 2024-01-18 22:07
Are you missing the meson package?
Try:

```
sudo pacman -S meson
```

**Comment by clsty** [comment] 2024-03-09 14:50
Closing, because:
- Since AGS evolves quickly, the issue is very likely to be outdated now.
- This is an AGS installation problem. Alhough I thank you for your feedback, there's not much we could do about it, except for the version controlling by specify the git commit hash of AGS repo in `scriptdata/installers`, which we have done already.

**Closed by clsty** 2024-03-09 14:50 UTC
